# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocNO', models.CharField(max_length=20, unique=True, verbose_name='\u8d44\u6599\u53f7')),
                ('Name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('FileName', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('Regtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('Rev', models.IntegerField(default=0, verbose_name='\u7248\u672c\u53f7')),
                ('isActive', models.BooleanField(default=True, verbose_name='\u662f\u5426\u751f\u6548')),
            ],
            options={
                'verbose_name': '\u6750\u6599',
                'verbose_name_plural': '\u6750\u6599\u6c47\u603b',
            },
        ),
        migrations.CreateModel(
            name='DrawingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('Size', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5c3a\u5bf8')),
            ],
            options={
                'verbose_name': '\u56fe\u5e45',
                'verbose_name_plural': '\u56fe\u5e45\u6c47\u603b',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6750\u6599',
                'verbose_name_plural': '\u6750\u6599\u6c47\u603b',
            },
        ),
        migrations.CreateModel(
            name='PDM_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='\u4ee3\u7801')),
                ('Name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u72b6\u6001',
                'verbose_name_plural': '\u72b6\u6001\u6c47\u603b',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5355\u4f4d',
                'verbose_name_plural': '\u5355\u4f4d\u6c47\u603b',
            },
        ),
    ]
